package com.cdd.back.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2016-11-30T13:47:30.739+08:00
 * Generated source version: 3.1.8
 * 
 */
@WebService(targetNamespace = "http://server.front.cdd.com/", name = "FrontWebServer")
@XmlSeeAlso({ObjectFactory.class})
public interface FrontWebServer {

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://server.front.cdd.com/FrontWebServer/createNewsDetailsRequest", output = "http://server.front.cdd.com/FrontWebServer/createNewsDetailsResponse")
    @RequestWrapper(localName = "createNewsDetails", targetNamespace = "http://server.front.cdd.com/", className = "com.cdd.back.client.CreateNewsDetails")
    @WebMethod
    @ResponseWrapper(localName = "createNewsDetailsResponse", targetNamespace = "http://server.front.cdd.com/", className = "com.cdd.back.client.CreateNewsDetailsResponse")
    public boolean createNewsDetails(
        @WebParam(name = "arg0", targetNamespace = "")
        com.cdd.back.client.MapConvertor arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://server.front.cdd.com/FrontWebServer/createHtmlRequest", output = "http://server.front.cdd.com/FrontWebServer/createHtmlResponse")
    @RequestWrapper(localName = "createHtml", targetNamespace = "http://server.front.cdd.com/", className = "com.cdd.back.client.CreateHtml")
    @WebMethod
    @ResponseWrapper(localName = "createHtmlResponse", targetNamespace = "http://server.front.cdd.com/", className = "com.cdd.back.client.CreateHtmlResponse")
    public java.lang.String createHtml(
        @WebParam(name = "arg0", targetNamespace = "")
        com.cdd.back.client.MapConvertor arg0
    );

    
//    @WebResult(name = "return", targetNamespace = "")
//    @Action(input = "http://server.front.cdd.com/FrontWebServer/__executeRequest", output = "http://server.front.cdd.com/FrontWebServer/__executeResponse")
//    @RequestWrapper(localName = "__execute", targetNamespace = "http://server.front.cdd.com/", className = "com.cdd.back.client.Execute")
//    @WebMethod(operationName = "__execute")
//    @ResponseWrapper(localName = "__executeResponse", targetNamespace = "http://server.front.cdd.com/", className = "com.cdd.back.client.ExecuteResponse")
//    public java.lang.Object execute(
//        @WebParam(name = "arg0", targetNamespace = "")
//        java.util.List<java.lang.Object> arg0,
//        @WebParam(name = "arg1", targetNamespace = "")
//        java.lang.Object arg1,
//        @WebParam(name = "arg2", targetNamespace = "")
//        java.lang.String arg2
//    );
}
