package com.cdd.back.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2016-11-30T13:47:30.764+08:00
 * Generated source version: 3.1.8
 * 
 */
@WebServiceClient(name = "frontWebServer", 
                  wsdlLocation = "http://localhost:9999/frontWebServer?wsdl",
                  targetNamespace = "http://server.front.cdd.com/") 
public class FrontWebServer_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://server.front.cdd.com/", "frontWebServer");
    public final static QName FrontWebServerImplPort = new QName("http://server.front.cdd.com/", "FrontWebServerImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:9999/frontWebServer?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(FrontWebServer_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:9999/frontWebServer?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public FrontWebServer_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public FrontWebServer_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FrontWebServer_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public FrontWebServer_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public FrontWebServer_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public FrontWebServer_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns FrontWebServer
     */
    @WebEndpoint(name = "FrontWebServerImplPort")
    public FrontWebServer getFrontWebServerImplPort() {
        return super.getPort(FrontWebServerImplPort, FrontWebServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FrontWebServer
     */
    @WebEndpoint(name = "FrontWebServerImplPort")
    public FrontWebServer getFrontWebServerImplPort(WebServiceFeature... features) {
        return super.getPort(FrontWebServerImplPort, FrontWebServer.class, features);
    }

}
